// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	models "github.com/NahuelDT/portfolio-api/internal/models"
	service "github.com/NahuelDT/portfolio-api/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// SearchServicer is an autogenerated mock type for the SearchServicer type
type SearchServicer struct {
	mock.Mock
}

// GetAssetDetails provides a mock function with given fields: id
func (_m *SearchServicer) GetAssetDetails(id uint) (*models.Instrument, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetDetails")
	}

	var r0 *models.Instrument
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Instrument, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Instrument); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Instrument)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchAssets provides a mock function with given fields: query
func (_m *SearchServicer) SearchAssets(query string) ([]service.SearchResult, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for SearchAssets")
	}

	var r0 []service.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]service.SearchResult, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []service.SearchResult); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByName provides a mock function with given fields: name
func (_m *SearchServicer) SearchByName(name string) ([]service.SearchResult, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []service.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]service.SearchResult, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []service.SearchResult); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByTicker provides a mock function with given fields: ticker
func (_m *SearchServicer) SearchByTicker(ticker string) (*service.SearchResult, error) {
	ret := _m.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for SearchByTicker")
	}

	var r0 *service.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*service.SearchResult, error)); ok {
		return rf(ticker)
	}
	if rf, ok := ret.Get(0).(func(string) *service.SearchResult); ok {
		r0 = rf(ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSearchServicer creates a new instance of SearchServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchServicer {
	mock := &SearchServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
