// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	models "github.com/NahuelDT/portfolio-api/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MarketDataRepositorer is an autogenerated mock type for the MarketDataRepositorer type
type MarketDataRepositorer struct {
	mock.Mock
}

// Create provides a mock function with given fields: marketData
func (_m *MarketDataRepositorer) Create(marketData *models.MarketData) error {
	ret := _m.Called(marketData)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.MarketData) error); ok {
		r0 = rf(marketData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLatestMarketData provides a mock function with given fields: instrumentID
func (_m *MarketDataRepositorer) GetLatestMarketData(instrumentID uint) (*models.MarketData, error) {
	ret := _m.Called(instrumentID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestMarketData")
	}

	var r0 *models.MarketData
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.MarketData, error)); ok {
		return rf(instrumentID)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.MarketData); ok {
		r0 = rf(instrumentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MarketData)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(instrumentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMarketDataRepositorer creates a new instance of MarketDataRepositorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketDataRepositorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketDataRepositorer {
	mock := &MarketDataRepositorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
