// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	models "github.com/NahuelDT/portfolio-api/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepositorer is an autogenerated mock type for the OrderRepositorer type
type OrderRepositorer struct {
	mock.Mock
}

// Create provides a mock function with given fields: order
func (_m *OrderRepositorer) Create(order *models.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *OrderRepositorer) GetByID(id uint) (*models.Order, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Order, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserCashBalance provides a mock function with given fields: userID
func (_m *OrderRepositorer) GetUserCashBalance(userID uint) (float64, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCashBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (float64, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) float64); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPositions provides a mock function with given fields: userID
func (_m *OrderRepositorer) GetUserPositions(userID uint) ([]models.Order, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPositions")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.Order, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.Order); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: orderID, status
func (_m *OrderRepositorer) UpdateStatus(orderID uint, status string) error {
	ret := _m.Called(orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderRepositorer creates a new instance of OrderRepositorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepositorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepositorer {
	mock := &OrderRepositorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
